baseURL: https://legaltech.uliege.be
languageCode: en-us
title: Liège LegalTech Lab
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/legaltech.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Liège LegalTech Lab
    # Hero subtitle (optional)
    subtitle: "de l'Université de Liège"
    # Button text
    buttontext: Présentation
    # Where the main hero button links to
    buttonlink: "/page/a-propos"
    # Hero image (from static/images/___)
    image: illustrations/legaltech.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - image: cris-uliege.png
      url: http://labos.ulg.ac.be/cris/
    - image: spiral-uliege.png
      url: http://www.spiral.ulg.ac.be
    - image: openjustice.png
      url: http://openjustice.be
    - image: cite-uliege.png
      url: http://cite.uliege.be
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Accueil
    url: /
  - title: À propos
    url: '/page/a-propos'
  - title: L'Équipe
    url: '/page/l-equipe'
  - title: Actualité
    sublinks:
    - title: Crédit d'opportunité
      url: /blog/credit-opportunite
    - title: Projet PDR
      url: /blog/pdr
  # - title: Corpus
  #   url: https://corpus.lltl.be
  #   button: true
  section1:
    title: Axes de travail
    subtitle: du Liège Legal Tech Lab (LLTL/ULiege) 
    tiles:
    - title: Recherche & Développement
      icon: mouse-globe
      text: Le LLTL étudie les initiatives legaltechs et en développe. 
      url: /page/vision
      buttonText: R&D
    - title: Accompagnement
      icon: laptop-cloud
      text: Le LLTL accompagne la conception de projets émergents.
      url: /page/vision
      buttonText: Interventions
    - title: Projet citoyen et politique
      icon: plug-cloud
      text: Le LLTL s'inscrit dans l'écosystème société.
      url: /page/vision
      buttonText: Enjeux
  section2:
    title: Axes de travail
    subtitle: Le Liège Legal Tech Lab (LLTL/ULiege) est composés de chercheurs issus de la Faculté de Droit et de la Faculté des Sciences Sociales. Ses activités de recherche et développement se situent dans le champ des technologies du droit et se déclinent autour de quatre axes de travail.
    features:
    - title: Axe 1 - Développement
      text: Martin Erpicum a développé un outil sous licence open source dédié́ à l’analyse qualitative et quantitative des textes juridiques (https://corpus.lltl.be). Destiné dans un premier temps aux chercheurs de la Faculté de Droit, une ouverture et une adaptation de l’outil à d’autres publics est envisageable par la suite (Barreaux, juridictions, administrations, services juridiques, etc.).
      icon: doc-sync

    - title: Axe 2 - Recherche
      text: Les plateformes, les infrastructures numériques et les projets legaltechs influencent les manières de faire le droit. Nous étudions la conception et la mise en œuvre de ces équipements ainsi que la recomposition des pratiques et des savoirs professionnels auxquels ils donnent lieu.  
      icon: laptop-globe

    - title: Axe 3 - Accompagnement et intervention
      text: Nous accompagnement la conception et le développement de projets legaltechs émergents. Nous organisons et contribuons également à des séminaires, webinaires et conférences sur ces thèmes.
      icon: doc-sync

    - title: Axe 4 - Projet citoyen et politique
      text: Nos activités s’inscrivent dans un écosystème où les relations avec les acteurs politiques, institutionnels, professionnels, entrepreneuriaux, académiques et associatifs sont primordiales et où l’ouverture (open science, open source, open government) constitue notre principe directeur.
      icon: doc-sync

  # section3:
  #   title: Une application
  #   subtitle: Application PoC pour l'analyse des textes juridiques
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Essayez-la!
  #   buttonLink: "http://corpus.lltl.be"
  # section4:
  #   title: Notre équipe
  #   subtitle: Équipe multidisciplinaire
  #   clients:
  #   - name: Pierre Delvenne
  #     quote: Membre fondateur
  #     job: Chercheur qualifié FNRS, Spiral
  #     img: pd
  #   - name: Christophe Dubois
  #     quote: Directeur
  #     job: Chargé de cours, CRIS
  #     img: cd
  #   - name: Martin Erpicum
  #     quote: Chercheur
  #     job: Chercheur & développeur
  #     img: me

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Suivez-nous
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/tintamarre/corpus/
      # Icons are from Font Awesome
      icon: github
    - link: https://github.com/openjusticebe/omdat
      # Icons are from Font Awesome
      icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: false
    quicklinks:
 
      column1:
        title: "Contacts"
        links:
        - text: L'équipe
          link: '/page/l-equipe'
        - text: ULiège
          link: 'https://uliege.be'
        - text: Cris
          link: 'http://labos.ulg.ac.be/cris/'
      # column2:
      #   title: "Documentation"
      #   links:
      #   - text: Accéder à la documentation
      #     link: http://docs.lltl.be/
      column3:
        title: "Developpements"
        links:
        - text: Corpus
          link: https://corpus.lltl.be
        - text: Omdat
          link: https://omdat.openjustice.lltl.be
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Carte blanche
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
